### ISSUE TITLE
Fix for OSX sifdecode

### ISSUE THREAD

**Issue by abelsiqueira** [optimizers/homebrew-cutest#20]
The failure on sifdecode is in line 126 of `src/decode/sifdecode_main.f90`.
Add `ACTION = 'READ'` and update `sifdecode.rb` accordingly.

Here's a [passing travis](https://travis-ci.org/abelsiqueira/homebrew-cutest/builds/112749804).

**Comment by dpo** [comment]
Thanks! Do you know why it would only be the `OPEN` of line 126?

**Comment by abelsiqueira** [comment]
[Travis line 2582](https://travis-ci.org/optimizers/homebrew-cutest/jobs/111131897#L2582)

**Comment by dpo** [comment]
Oh right, so if we fix line 126, the same error will occur with the subsequent `OPEN` statements, right?

**Comment by abelsiqueira** [comment]
Not really, that `open` statement opens the SIF, which is outside the sandbox environment.
The other `open`s affect only local files.
Maybe a good practice would be to qualify all `open`s.

[Here's the Travis of my debug](https://travis-ci.org/abelsiqueira/homebrew-cutest/builds/112711829)

**Comment by lrsantos11** [comment]
Guys, could not install on my MacOs CUTEst. This error keep occurring. Any news?

**Comment by dpo** [comment]
You get this error locally on OSX? What do you mean that you could not install? This error occurs at run time, not at install time.

**Comment by lrsantos11** [comment]
@dpo I'm with a problem with CUTEst on macOS. In fact, I could install on my MacbookAir (running like a charm), however on my server, the installation of gsl@1 is failing. Here is the gist
https://gist.github.com/lrsantos11/eca926a588a49946879b3f1e6736da36
In fact, version 0.4 is installed, but the upgrade to ever

I don't know what is wrong here and I'll be glad if any of you guys could help me.
Cheers,

Rafa

**Comment by dpo** [comment]
@lrsantos11 Please open a new issue as your compilation error is unrelated to the topic of this issue. Thanks.

**Comment by lrsantos11** [comment]
I don't know what happened, but it's working now. Sorry for commenting on another issue.

**Comment by dpo** [comment]
Closing this as I released precompiled binaries for all formulae. Please open a new issue if difficulties persist.
