### ISSUE TITLE
Decoding error

### ISSUE THREAD

**Issue by frankecurtis** [optimizers/homebrew-cutest#22]
I'm worried Matlab may be causing the issue, but here goes...

I'm trying to use CUTEst with Matlab, but I get an error when decoding using cutest2matlab.  I'll post the error message below.

Details:  I'm running OS X El Capitan and have Matlab R2016a.  CUTEst was installed using Homebrew, which appeared to go smoothly.  (There were no errors running "brew test cutest".)  However, an error popped up running cutest2matlab.

Issues I've had in the past were cleared up using gfortran 4.3, but, as you may know, trying "brew install gcc43" on El Capitan doesn't work; an error pops up saying that it only compiles on Mavericks or older.

Any way to fix this?  Errors copied below...
# 

sifdecoder -A mac64.osx.gfo -st   bt3

 Problem name: bt3

 Double precision version will be formed

 The objective function uses 1 nonlinear group

 There are 3 linear equality constraints

 There are 5 free variables

 File successfully decoded
/Users/frankecurtis/Dropbox/shared/DanielMohammadreza/projects/funnel/matlab/src
 CUTEST: tools (double precision version) compiled successfully
 Compiling mcutest              Building with 'Xcode with Clang'.
/usr/local/Cellar/cutest/0.2/libexec/objects/mac64.osx.gfo/double/mcutest.c:108:13: error: typedef redefinition with different types ('int' vs 'size_t' (aka 'unsigned long'))
typedef int mwSize;
            ^
/Applications/MATLAB_R2016a.app/extern/include/tmwtypes.h:795:19: note: previous definition is here
typedef size_t    mwSize;         /\* unsigned pointer-width integer _/
                  ^
/usr/local/Cellar/cutest/0.2/libexec/objects/mac64.osx.gfo/double/mcutest.c:109:13: error: typedef redefinition with different types ('int' vs 'size_t' (aka 'unsigned long'))
typedef int mwIndex;
            ^
/Applications/MATLAB_R2016a.app/extern/include/tmwtypes.h:796:19: note: previous definition is here
typedef size_t    mwIndex;        /_ unsigned pointer-width integer _/
                  ^
/usr/local/Cellar/cutest/0.2/libexec/objects/mac64.osx.gfo/double/mcutest.c:1086:9: warning: '/_' within block comment [-Wcomment]
        /\* Finalize sparse data structure for sparse gradient _/
        ^
/usr/local/Cellar/cutest/0.2/libexec/objects/mac64.osx.gfo/double/mcutest.c:1087:53: warning: '/_' within block comment [-Wcomment]
        /\* for (i = 0; i < nnzgci; i++) ir[i]--;    /\* 0-based indexing */
                                                    ^
2 warnings and 2 errors generated.

make: **\* [/usr/local/opt/cutest/libexec/objects/mac64.osx.gfo/double/mcutest.o] Error 255
Building with 'Xcode Clang++'.
clang: error: no such file or directory: '/usr/local/opt/cutest/libexec/objects/mac64.osx.gfo/double/mcutest.o'

**Comment by dpo** [comment]
Frank, sorry I must have missed your message somehow. Someone else reported a similar error. I think it's something about Matlab 2016. I don't have access to it yet to test, but if you still have access to a 2015 version, that'd be the fastest way to get you off the ground.

Unfortunately, gcc-4.3 isn't supported in Homebrew anymore but the good news is that I've been using newer versions of gcc and gfortran on OSX with Matlab and things seem to be working.

Sorry this isn't a more definitive fix. I'll look into it when I have Matlab 2016 handy.

**Comment by dpo** [comment]
#26 fixes this.
