### ISSUE TITLE
Matlab sparse matrix functions need "-largeArrayDims"

### ISSUE THREAD

**Issue by bstellato** [optimizers/homebrew-cutest#28]
When I use functions such as `cutest_sphess` from the Matlab interface, I get the following error on OSX and Matlab 2016b:

```
Function "mxGetIr" is obsolete.
(64-bit mex files using sparse matrices must be rebuilt with the "-largeArrayDims" option.  See the R2006b release notes for more
details.)
```

I think the cutest bottle need to be updated with that compiler flag.

**Comment by dpo** [comment]
This tap doesn't ship any bottles. But it's true that CUTEst itself should let the user pass `-largeArrayDims` when a mex file is compiled. I'll add that feature soon. Thanks.
