### ISSUE TITLE
How to make Maros-Mezaros or Netlib collections be read?

### ISSUE THREAD

**Issue by lrsantos11** [optimizers/homebrew-cutest#32]
According to @abelsiqueira, the only way to make Maros-Mezaros collection be recognized and available to use (on CUTEst.jl, for instance), is to copy-past the whole collection to mastsif folder. 

@dpo, do you know any other way? You created the formula for Maros_Mezaros. Probably one should have to change CUTEst installation to:
1. Read subfolders into `mastsif/share/mastsif` folder and thus we only would have to make a symbolic link to maros_mezaros ou netlib; or
1. read others folders.

Any ideias?

**Comment by dpo** [comment]
It's possible that you could reset the `MASTSIF` environment variable to the location of the MM problems. I haven't tested with CUTEst.jl.

**Comment by lrsantos11** [comment]
Perfect. 
I just used `export MASTSIF="path/to/MM"` and initialized `julia`. 
All working perfect. 
Thanks @dpo

**Comment by dpo** [comment]
Please do. Thanks!
