### ISSUE TITLE
Issue upgrading archdefs: undefined method `prefer_64_bit?' for OS::Mac:Module 

### ISSUE THREAD

**Issue by jfowkes** [optimizers/homebrew-cutest#42]
Hello, 

I get the following error when trying to upgrade archdefs:

```
==> Upgrading optimizers/cutest/archdefs 
Error: An exception occurred within a child process:
  NoMethodError: undefined method `prefer_64_bit?' for OS::Mac:Module
```

Any thoughts on how to fix this?

**Comment by dpo** [comment]
I think so. I should be able to find some time to fix it later today. Thanks for the report.

**Comment by dpo** [comment]
Should be fixed as soon as I update `sifdecode` and `cutest`.

**Comment by jfowkes** [comment]
That's great, many thanks for the quick fix.

**Comment by dpo** [comment]
Should be good to go. Let me know if anything's still not working for you.
