### ISSUE TITLE
trouble with "brew install mastsif"

### ISSUE THREAD

**Issue by optcutestinstall** [optimizers/homebrew-cutest#50]
When I tried to install mastsif, I got an error:

curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "mastsif"
Download failed: https://bitbucket.org/optrove/sif/get/v0.5.tar.bz2

Does anyone know how to deal with this problem?

**Comment by dpo** [comment]
It works for me. Wait a little while and try again to make sure it's not an intermittent network issue.

**Comment by optcutestinstall** [comment]
Install successfully after restart the computer.
