### ISSUE TITLE
trouble with "cutest2matlab LUBRIFC"

### ISSUE THREAD

**Issue by optcutestinstall** [optimizers/homebrew-cutest#51]
I installed cutest [--with-matlab] [--without-single] [--with-pgi]
After setting
export MYMATLABARCH="mac64.osx.gfo"
export MYARCH="mac64.osx.gfo"
I tried to decode a problem as given in "cutest-mirror/src/matlab/README.matlab" and  input "cutest2matlab LUBRIFC"
The output as:
mac64.osx.gfo
 The architecture privided by the environment variables MYMATLABARCH and MYARCH has not been installed. Install a gfortran version of CUTEst unsing install_cutest and re-run.

Does anybody know what to do next?

**Comment by dpo** [comment]
> cutest [--with-matlab] [--without-single] [--with-pgi]

That is not a command. The brackets are UNIX notation to indicate optional arguments.

What is the exact command that you used? `brew install cutest --with-matlab`? What is the output of `ls -R $CUTEST/objects`?

**Comment by optcutestinstall** [comment]
$ ls -R $CUTEST/objects



mac64.osx.gfo




/usr/local/Cellar/cutest/2.0.2/libexec/objects/mac64.osx.gfo:

doublesingle




/usr/local/Cellar/cutest/2.0.2/libexec/objects/mac64.osx.gfo/double:

algencan_main.odirectsearch_main.ogenc_main.olibcutest_double.dylibosqp_main.ostats_main.o

bobyqa_main.ofiltersd_main.ohrb_main.olincoa_main.opds_main.ostenmin_main.o

ccutest.cfiltersqp_main.oipopt_main.oloqo_main.opennlp_main.otenmin_main.o

cg_descent_main.ogen77.oknitro_main.ominos_main.opraxis_main.otest_main.o

cgplus_main.ogen77_main.ola04_main.onewuoa_main.oql_main.otron_main.o

cobyla_main.ogen90.olbfgs_main.onitsol_main.oqplib_main.ouncmin_main.o

derchk_main.ogen90_main.olbfgsb_main.onlpqlp_main.osnopt_main.ovf13_main.o

dfo_main.ogenc.olibcutest.anpsol_main.ospg_main.oworhp_main.o




/usr/local/Cellar/cutest/2.0.2/libexec/objects/mac64.osx.gfo/single:

algencan_main.odirectsearch_main.ogenc_main.olibcutest_single.dylibosqp_main.ostenmin_main.o

bobyqa_main.ofiltersd_main.ohrb_main.olincoa_main.opds_main.otenmin_main.o

ccutest.cfiltersqp_main.oipopt_main.oloqo_main.opennlp_main.otest_main.o

cg_descent_main.ogen77.oknitro_main.ominos_main.opraxis_main.otron_main.o

cgplus_main.ogen77_main.ola04_main.onewuoa_main.oql_main.ouncmin_main.o

cobyla_main.ogen90.olbfgs_main.onitsol_main.osnopt_main.ovf13_main.o

derchk_main.ogen90_main.olbfgsb_main.onlpqlp_main.ospg_main.oworhp_main.o

dfo_main.ogenc.olibcutest.anpsol_main.o







At 2019-07-07 01:02:15, "Dominique" <notifications@github.com> wrote:


cutest [--with-matlab] [--without-single] [--with-pgi]

That is not a command. The brackets are UNIX notation to indicate optional arguments.

What is the exact command that you used? brew install cutest --with-matlab? What is the output of ls -R $CUTEST/objects?

**Comment by dpo** [comment]
On macOS, you need to use `cutest2matlab_osx LUBRIFC`.

**Comment by optcutestinstall** [comment]
I tried to use  cutest2matlab_osx LUBRIFC, it retured simlar error:



#  check that the architecture provided in MYMATLABARCH or MYARCH exists




if [[ ! -e $CUTEST/versions/$ARCH ]] ; then

    echo ' The architecture privided by the environment variables MYMATLABARCH'

    echo '  and MYARCH has not been installed. Install a gfortran version of'

    echo ' CUTEst unsing install_cutest and re-run.'

    exit 2

fi

+ [[ ! -e /versions/mac64.osx.gfo ]]

+ echo ' The architecture privided by the environment variables MYMATLABARCH'

 The architecture privided by the environment variables MYMATLABARCH

+ echo '  and MYARCH has not been installed. Install a gfortran version of'

  and MYARCH has not been installed. Install a gfortran version of

+ echo ' CUTEst unsing install_cutest and re-run.'

 CUTEst unsing install_cutest and re-run.

+ exit 2













At 2019-07-07 01:25:06, "Dominique" <notifications@github.com> wrote:


On macOS, you need to use cutest2matlab_osx LUBRIFC.

**Comment by optcutestinstall** [comment]
Indeed. Now, I use cutest2matlab_osx LUBRIFC and File successfully decoded.
However, there is a new problem:



# build and link mex file

[[ -f ${PWD}/mcutest.o ]] || ${MYMATLAB}/bin/mex -c -I${CUTEST}/include ${CUTEST}/src/matlab/mcutest.c

+ [[ -f /Users/**/mcutest.o ]]

${MYMATLAB}/bin/mex -I${CUTEST}/include -output mcutest -L${PWD} -l${PROB} -lcutest  mcutest.o

+ /Applications/MATLAB_R2018a.app/bin/mex -I/usr/local/Cellar/cutest/2.0.2/libexec/include -output mcutest -L/Users/** -lLUBRIFC -lcutest mcutest.o

ʹ?? 'Xcode with Clang' ???

xcrun: error: SDK "macosx10.14.4" cannot be located




xcrun: error: SDK "macosx10.14.4" cannot be located

ld: library not found for -lcutest

clang: error: linker command failed with exit code 1 (use -v to see invocation)







So far, I only install xcode command line tools and the output of "xcode-select -p" is 




/Library/Developer/CommandLineTools







At 2019-07-07 01:25:06, "Dominique" <notifications@github.com> wrote:


On macOS, you need to use cutest2matlab_osx LUBRIFC.

**Comment by optcutestinstall** [comment]
It works after I install xcode.
