### ISSUE TITLE
WARNING: NSWindow drag regions should only be invalidated on the Main Thread!

### ISSUE THREAD

**Issue by optcutestinstall** [optimizers/homebrew-cutest#52]
I tried to decode a problem and load it up in Matlab. I input
$ cutest2matlab_osx LUBRIFC
It exited as       exit 0;
Then I input $ matlab &
when matlab was turned on, the following warning was displayed on my computer terminal:

2019-07-07 12:23:15.901 MATLAB_maci64[22129:594056] WARNING: NSWindow drag regions should only be invalidated on the Main Thread! This will throw an exception in the future. Called from (
	0   AppKit                              0x00007fff33cad7eb -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 378
	1   AppKit                              0x00007fff33caabdb -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1479
	2   AppKit                              0x00007fff33caa60e -[NSWindow initWithContentRect:styleMask:backing:defer:] + 45
	3   libnativewindow_macosx.jnilib       0x0000000121773f05 Java_jogamp_nativewindow_macosx_OSXUtil_CreateNSWindow0 + 421
	4   ???                                 0x000000012551f9f4 0x0 + 4921096692
)

Does anyone know how to deal with this problem?

**Comment by dpo** [comment]
Sorry that is not a question related to CUTEst or to the Homebrew formulae provided here.
