### ISSUE TITLE
 ERROR: A compilation error occurred. Fix for OSX sifdecode

### ISSUE THREAD

**Issue by ghost** [optimizers/homebrew-cutest#54]
I am trying to install CUTEst on my Mac Pro 2019 from here 

  https://github.com/optimizers/homebrew-cutest
in this step 
```
brew install cutest [--with-matlab] [--without-single] [--with-pgi]
```
I end up with this final lines of errors:
```
Last 15 lines from /Users/naghmeh/Library/Logs/Homebrew/sifdecode/01.install_sifdecode:
collect2: error: ld returned 1 exit status
[ OK ]
 sifdecode: tools packages (double precision version) compiled successfully
 Compiling random         		[ OK ]
 Compiling check_derivs   		[ OK ]
 Compiling check_derivs_main		[ OK ]
 sifdecode: check packages (double precision version) compiled successfully
 Compiling slct           		ld: unexpected token: !tapi-tbd-v3 file '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd' for architecture x86_64
collect2: error: ld returned 1 exit status
make[1]: *** [/private/tmp/sifdecode-20190820-22611-186rgoc/SIFDecode-2.0.1/objects/mac64.osx.gfo/double/slct.o] Error 1
make: *** [all_double] Error 2

 ERROR: A compilation error occurred.


If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/optimizers/homebrew-cutest/issues

These open issues may also help:
Fix for OSX sifdecode https://github.com/optimizers/homebrew-cutest/issues/20
```

**Comment by dpo** [comment]
> Compiling slct ld: unexpected token: !tapi-tbd-v3 file '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd' for architecture x86_64
collect2: 

I believe this is an issue with your local Xcode and/or command-line tools (CLT) installation. Could you try reinstalling the CLT or installing a fresh Xcode?

**Comment by naghmeh6** [comment]
naghmehs-MacBook-Pro:~ naghmeh$ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates

**Comment by dpo** [comment]
Try following the steps of this StackOverflow answer: https://stackoverflow.com/questions/17980759/xcode-select-active-developer-directory-error/17980786#17980786

**Comment by dpo** [comment]
Were you able to solve your issue with the instructions above?

**Comment by naghmeh6** [comment]
no I use OSQP

**Comment by dpo** [comment]
I just released precompiled binaries for Catalina and Big Sur, so such error should no longer happen. However, feel free to open a new issue if difficulties persist.
