### ISSUE TITLE
SIFDecode issue

### ISSUE THREAD

**Issue by melodyqxuan** [optimizers/homebrew-cutest#57]
Hi, I tried to install CUTEST and test SIFDecode but encountered the following issue:

$ brew test sifdecode
Testing optimizers/cutest/sifdecode
==> /usr/local/Cellar/sifdecode/2.0.1/bin/sifdecoder /usr/local/opt/sifdecode/li
Last 15 lines from /Users/melody/Library/Logs/Homebrew/sifdecode/test.01.sifdecoder:
2020-07-31 13:01:02 -0500

/usr/local/Cellar/sifdecode/2.0.1/bin/sifdecoder
/usr/local/opt/sifdecode/libexec/sif/ROSENBR.SIF

dyld: Library not loaded: /usr/local/opt/gcc/lib/gcc/9/libgfortran.5.dylib
Referenced from: /usr/local/opt/sifdecode/libexec/objects/mac64.osx.gfo/double/run_sifdecode
Reason: image not found
/usr/local/Cellar/sifdecode/2.0.1/bin/sifdecoder: line 451: 7266 Abort trap: 6 $DECODER

ERROR: Error exit from decoding stage. terminating execution.

Error: optimizers/cutest/sifdecode: failed
An exception occurred within a child process:
BuildError: Failed executing: /usr/local/Cellar/sifdecode/2.0.1/bin/sifdecoder /usr/local/opt/sifdecode/libexec/sif/ROSENBR.SIF
/usr/local/Homebrew/Library/Homebrew/formula.rb:2010:in block in system' /usr/local/Homebrew/Library/Homebrew/formula.rb:1948:in open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1948:in system' /usr/local/Homebrew/Library/Taps/optimizers/homebrew-cutest/sifdecode.rb:77:in block (2 levels) in class:Sifdecode'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:128:in chdir' /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:128:in cd'
/usr/local/Homebrew/Library/Taps/optimizers/homebrew-cutest/sifdecode.rb:76:in block in <class:Sifdecode>' /usr/local/Homebrew/Library/Homebrew/formula.rb:1818:in block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/utils.rb:474:in with_env' /usr/local/Homebrew/Library/Homebrew/formula.rb:1817:in block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:900:in with_logging' /usr/local/Homebrew/Library/Homebrew/formula.rb:1816:in block in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2060:in block in mktemp' /usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in chdir' /usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in run'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2059:in mktemp' /usr/local/Homebrew/Library/Homebrew/formula.rb:1810:in run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:35:in block in <main>' /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:93:in block in timeout'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:33:in block in catch' /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:33:in catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:33:in catch' /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:108:in timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:34:in `<main>'

I'm wondering if you can help me with this. Many thanks!

**Comment by dpo** [comment]
Hi. You closed the issue. Were you able to resolve the problem?

**Comment by melodyqxuan** [comment]
Yes, it seems that the issue is solved after I reinstall SIFDecode separately. Thanks!
