### ISSUE TITLE
Errno::ENOENT: No such file or directory @ dir_chdir - objects/pc64.lnx.gfo/single

### ISSUE THREAD

**Issue by tnnguyen103** [optimizers/homebrew-cutest#58]
When I try to install cutest by typing : brew install cutest, I receive an error as follows. 

Updating Homebrew...
==> Installing cutest from optimizers/cutest
==> Downloading https://github.com/ralna/CUTEst/archive/v2.0.2.tar.gz
Already downloaded: /home/thuan/.cache/Homebrew/downloads/19e24677b1620da0b5e5f79ce1bfc503b2eac3c4f76af8a0797076ef84b98116--CUTEst-2.0.2.tar.gz
==> Patching
patching file bin/install_cutest_alone
==> ./install_cutest < cutest.input
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory @ dir_chdir - objects/pc64.lnx.gfo/single

Could you help me to fix this issue, please? Thank you in advance.

**Comment by dpo** [comment]
Sorry I must have missed this issue. I just released precompiled binaries for all formulae in this tap. Hopefully that resolves the problem. Please feel free to open a new issue if difficulties persist.
