### ISSUE TITLE
Bump to CUTEst 2.0.60

### ISSUE THREAD

**Issue by jfowkes** [optimizers/homebrew-cutest#73]
@dpo CUTEst 2.0.57 is failing for me due an unguarded float128 typedef in `cutest.h`
```
/opt/homebrew/opt/cutest/libexec/include/cutest.h:60:9: error: __float128 is not supported on this target
typedef __float128   quadreal;
        ^
1 error generated.
error: command '/usr/bin/clang' failed with exit code 1
``` 
This has been fixed in CUTEst 2.0.60 via an include guard in the `cutest.h` header by @amontoison

**Comment by dpo** [comment]
Yes. I reported that problem https://github.com/ralna/CUTEst/issues/48. For some reason, it wasn't an issue on the GitHub VM. I'll update the formula, but doesn't Homebrew pour the bottle on your machine? Why are you compiling from source?

**Comment by jfowkes** [comment]
Ah sorry didn't see your bug report. Yes homebrew does pour the precompiled bottle, this happens when I try to use the faulty header to compile a CUTEst interface using PyCUTEst.
