### ISSUE TITLE
CUTEst macOS bottles missing

### ISSUE THREAD

**Issue by jfowkes** [optimizers/homebrew-cutest#79]
I noticed that the precompiled macOS bottles for CUTEst appear to be missing:
```rb
bottle do
    root_url "https://github.com/optimizers/homebrew-cutest/releases/download/cutest-2.1.0"
    sha256 cellar: :any_skip_relocation, x86_64_linux: "604b12791912e0acccbda1110e9eb6778223d1d3a5cb79464beb2f1c87119fb4"
end
```
whereas they used to be provided. Is this by design?

**Comment by dpo** [comment]
No, not by design at all. I forgot to rebuild the gsl dependency. It’s on the way. Thanks for reporting. I missed it.

**Comment by dpo** [comment]
Should be good now.
